#
# Module manifest for module 'SecretsManager'
#
# Generated by: -- redacted --
#
# Generated on: 12/4/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SecretsManager.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '99d624d3-609c-43d8-ba14-2b15c6cc83a9'

# Author of this module
Author = '-- redacted --'

# Company or vendor of this module
CompanyName = '-- redacted --'

# Copyright statement for this module
Copyright = '-- redacted --'

# Description of the functionality provided by this module
Description = 'Module to manager user secrets'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-UserSecret', 'New-UserSecretsFile', 'Remove-AllUserSecrets', 
               'Remove-UserSecret', 'Set-AllUserSecrets', 'Set-UserSecret', 
               'Show-AllUserSecrets'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()
}

